name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the project
        run: yarn build

      - name: Copy build to web directory
        run: |
          sudo rm -rf /var/www/host/InLeave
          sudo mkdir -p /var/www/host/InLeave
          sudo cp -r dist/* /var/www/host/InLeave/

      - name: Restart Nginx
        run: sudo systemctl restart nginx